apiVersion: v1
kind: Service
metadata:
  name: windows-app1-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: windows-app1
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP