apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-class
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain 
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageAccounttype: Premium_LRS
  kind: managed